language: php
php:
  - 8.2.2
dist: focal

env:
  - TEST_GROUP=m23
  - TEST_GROUP=m24
  - TEST_GROUP=m24nodb
  - TEST_GROUP=m2451nodb

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer self-update --2
  - composer validate
  - composer install
# Run static analysis tests before trying to install the modules in magento
  - composer test:static
  - composer test:phpstan
# Run unit tests before trying to install magento
  - composer test:unit
  - cd dev
  - docker --version
  - make docker-up ENV=$TEST_GROUP
  - docker ps
  - make docker-install ENV=$TEST_GROUP

script:
  - make docker-test ENV=$TEST_GROUP

services:
  - docker

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
